// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9OuO3XNbqRcuBU-Wlpq9fomOkUMbzTnE',
    appId: '1:972515775153:web:2a5cfff44bde1cd5c9c890',
    messagingSenderId: '972515775153',
    projectId: 'counseling-659c1',
    authDomain: 'counseling-659c1.firebaseapp.com',
    storageBucket: 'counseling-659c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2iyZpdkVeLEJ_LWdYhusdbmc8S1KlnF0',
    appId: '1:972515775153:android:9877fec3b0d2feebc9c890',
    messagingSenderId: '972515775153',
    projectId: 'counseling-659c1',
    storageBucket: 'counseling-659c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXE7-YGxkmWbtdIEhNSV0kaQpNfJtsVXo',
    appId: '1:972515775153:ios:55c5c6b18a75d691c9c890',
    messagingSenderId: '972515775153',
    projectId: 'counseling-659c1',
    storageBucket: 'counseling-659c1.appspot.com',
    iosClientId: '972515775153-k7lqnvnj6quu64bqdtg36qt80u85uflm.apps.googleusercontent.com',
    iosBundleId: 'com.example.careapp',
  );
}
